#!/bin/sh

alias \
    surf="tabbed surf -pe" \
    surfnotabbed="command surf" \
	dotfiles="git --git-dir=$HOME/dotfiles --work-tree=$HOME" \
	wp-random="feh --bg-fill -z /home/skye/wallpapers/*/*" \
	cl="clear"


